### ISSUE TITLE
【脚本】部署 github

### ISSUE THREAD

**Issue by Erindcl** [DTStack/ant-design-dtinsight-theme#10]
## 使用脚本部署至 github 上
1. 将功能合并至 `dev_build` 分支
2. 使用 `dev_build` 分支打包生成 `dist` 文件夹
3. 将 `dist` 文件夹中的目录同步至 `gh-pages` 分支

**Comment by ting0130** [comment]
集成 **gh-pages** 工具推送 dist 目录下的文件
