### ISSUE TITLE
弹窗相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#106]
底部操作按钮文字未上下居中对齐按钮
![image](https://user-images.githubusercontent.com/92357451/172984393-9670f701-9d96-4b26-bbd6-cdefa0025ea9.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/172986412-b16c1f49-a677-4056-adf7-298ae5dde6cf.png)
当表格中没有输入框/下拉框的表格的时候，表格单行高度统一36px，当有输入框/下拉框等可编辑的内容的时候，表格单行高度为44px

![image](https://user-images.githubusercontent.com/92357451/172986780-5e54a0ea-bbcc-4caf-a939-30fe40408c6c.png)
表头高度跟表格单行高度要一样

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174239252-bf20e876-4fc1-4d46-bd4a-80835d7ae95a.png)
未修改

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174733929-f83ec98d-6c39-4e9d-b8b4-a8c33c81cb30.png)
设计稿：
![image](https://user-images.githubusercontent.com/99383821/174733979-c4a902cd-0f3e-4c0c-ad9c-323987935cdd.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174735693-abc8c926-82aa-4485-9495-644944b5bd04.png)
设计稿：
![image](https://user-images.githubusercontent.com/99383821/174735769-446952d9-342b-406e-ab1e-6632a232d93f.png)
![image](https://user-images.githubusercontent.com/99383821/174736300-6c474054-3121-4c86-900b-b31ebccdb679.png)
![image](https://user-images.githubusercontent.com/99383821/174736299-fc93f053-097b-4b0f-a7d3-ca42d224c76c.png)
