### ISSUE TITLE
复选框相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#109]
失效状态和已选失效状态未展示出来
![image](https://user-images.githubusercontent.com/92357451/173005398-2e6857cc-3ec5-489e-a4d1-21674dfd7c23.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/178953211-06d737c6-2aac-4be4-a541-37b9eab290cd.png)
