### ISSUE TITLE
表单相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#111]
数量输入框的宽度为100px，这部分内容再设计规范的输入框模块
![image](https://user-images.githubusercontent.com/92357451/173272069-eab77178-8d42-4009-b9d6-4554ae8585c0.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174237119-25523406-6a3e-46c9-8940-d17248b30669.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174237261-b265ae5a-3270-45ce-a069-48dbfe25e212.png)

**Comment by daxi1** [comment]
单选居中问题还未解决
![image](https://user-images.githubusercontent.com/99383821/179198232-151c92fd-3717-4122-960a-92b3b35806dc.png)
