### ISSUE TITLE
单选框相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#112]
缺失已选失效状态
![image](https://user-images.githubusercontent.com/92357451/173277252-dde42dea-c7be-488b-8697-44244c48c1ce.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/173277492-1359707c-34de-4eb0-b82c-ddcfccbf8b10.png)
文字和icon未上下居中对齐

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174236084-cbea4ed1-0f19-46c1-8660-d86180223d3b.png)
