### ISSUE TITLE
时间选择框相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#113]
按钮尺寸为24px；按钮文本是确定和此刻；按钮文本未与按钮上下居中对齐
![image](https://user-images.githubusercontent.com/92357451/173288012-00ff3c04-1905-4b90-8aec-5985f36e87cf.png)

**Comment by daxi1** [comment]
1、![image](https://user-images.githubusercontent.com/99383821/174234506-a28f82b1-bb18-4f4e-83e0-0490e6b4f1ea.png)
2、
![image](https://user-images.githubusercontent.com/99383821/174235470-058f7873-68d4-4e29-949f-69293a539998.png)
3、
![image](https://user-images.githubusercontent.com/99383821/174235791-6fd0cfac-3a59-4f5d-9632-ec8419a1746d.png)
4、
![image](https://user-images.githubusercontent.com/99383821/174235878-987deb27-bbb9-4d2b-a732-0d7f9a0064bb.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/179462823-c2bfe966-51aa-4327-9a9d-884bcf7a371c.png)
按钮没有居中
