### ISSUE TITLE
上传相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#114]
![image](https://user-images.githubusercontent.com/92357451/173293450-341fa997-800d-4788-90dc-18e9153f1d65.png)
1. 上传中的状态进度条位置不对，填充颜色不对
2. 上传失败的状态样式不对，删除icon不对，上传失败的时候有重新上传的icon
![image](https://user-images.githubusercontent.com/92357451/173293785-c5ce539d-162b-475b-bc0e-f378ff95ea43.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174234187-e7467aee-f1b5-4d3f-a70f-11735b3e5059.png)
