### ISSUE TITLE
数据录入模块缺失穿梭框内容

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#115]

**Comment by daxi1** [comment]
1、文案按照设计稿给出的内容
![image](https://user-images.githubusercontent.com/99383821/174233108-b78b2bd7-194b-492a-84e7-0d8710fc1f05.png)
![image](https://user-images.githubusercontent.com/99383821/174233157-ae272482-4e8a-422d-95f8-5a9952d64575.png)
2、
![image](https://user-images.githubusercontent.com/99383821/174233676-5406e15b-8a07-4aaa-9795-f1629c6668f7.png)
3、
![image](https://user-images.githubusercontent.com/99383821/174233954-0fc45c6f-7401-40f6-8a71-42cc9e68a32f.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/179200752-4a2984fd-a201-48a1-a868-caefad58e277.png)
![image](https://user-images.githubusercontent.com/99383821/179200969-d2ef6a5d-8f01-45a6-a6d4-2d432ba77864.png)
![image](https://user-images.githubusercontent.com/99383821/179201174-27a16655-1d96-4c4c-9b98-a058d6719801.png)
