### ISSUE TITLE
折叠面板相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#116]
1. 文本内容距离上下边框间距为10px
2. 标题需要加粗
![image](https://user-images.githubusercontent.com/92357451/173301626-60fb5f22-1822-461d-836b-62363640c48b.png)
![image](https://user-images.githubusercontent.com/92357451/173301823-4f2e864a-fb22-45e4-a32e-98d8dd0af553.png)

3. 内容背景缺失一块
![image](https://user-images.githubusercontent.com/92357451/173302472-ef18d6f8-831c-455e-a3fd-5f07c0a1c253.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174222461-13e8d9c8-76fc-4532-ab22-4432621eb9bd.png)
![image](https://user-images.githubusercontent.com/99383821/174222556-a79c0f11-7e91-4601-858a-3d2556d824eb.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/181707817-764c14a8-0605-450f-90ca-6ad08ff67bb0.png)
