### ISSUE TITLE
描述列表相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#117]
![image](https://user-images.githubusercontent.com/92357451/173303543-9eb20366-fce9-471a-b5d1-842ec609d819.png)
多行的文字情况，上下间距依然保持8px的间距

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/173305900-d91bd2fe-3405-4cca-a8ef-d2ca9ea50f21.png)
圆角这里格式不对，去掉圆角吧

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174222077-72484fe4-c467-4a62-9b52-1a30ac4cfc6e.png)
字体行高20px
