### ISSUE TITLE
气泡提示相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#119]
缺失多种情景的样式
![image](https://user-images.githubusercontent.com/92357451/173310514-a9bb4896-ea8a-4a48-9e0d-7515d628745f.png)
![image](https://user-images.githubusercontent.com/92357451/173310585-cbbb0681-008e-4bc2-ba47-83c09e3de261.png)
![image](https://user-images.githubusercontent.com/92357451/173310658-af247193-4d1a-4dc3-b23c-2660f26c08ce.png)

**Comment by daxi1** [comment]
未修改

**Comment by shiqiWang0** [comment]
已经修复了， 没有重新部署

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/180381149-50329461-4940-45a4-9028-ffe1850ffa3b.png)
![image](https://user-images.githubusercontent.com/99383821/180381387-8efd80a2-880f-44d5-8533-ae0217c81d44.png)
![image](https://user-images.githubusercontent.com/99383821/180381678-7385ea1f-c6e3-43a6-acb1-333b73cad848.png)
![image](https://user-images.githubusercontent.com/99383821/180381731-1d88af56-9d49-412f-be38-36e0804e872d.png)
