### ISSUE TITLE
分页器相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#120]
1. 12px的文字高度统一都是20px，页码选择框内的文字高度为20px，这样24px的外边框上下各是2px的间距
![image](https://user-images.githubusercontent.com/92357451/173311743-38316f43-c191-4918-aaec-43aaee0b0470.png)

2. 这里的文字颜色是#8B8FA8
![image](https://user-images.githubusercontent.com/92357451/173312340-c2520adc-db84-453a-9f1f-8285c3a2ce1a.png)

**Comment by fayfayfairy** [comment]
显示内容上，中英文最好统一一下，要么都是中文，要么都是英文
![image](https://user-images.githubusercontent.com/92357451/173313272-987cf1df-0497-45d4-9193-74d5ece7be07.png)

**Comment by shiqiWang0** [comment]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/47959147/173757739-4f3cd93b-7f6f-482a-aa28-00a0909d11c9.png">
这个地方，不是样式可以修改的；目前的精简型组件是不支持前面的总数注释的；已经和@fayfayfairy沟通对齐

**Comment by daxi1** [comment]
图标大小占位
![image](https://user-images.githubusercontent.com/99383821/174219865-38e436d5-1fb1-42d2-bd0b-0071b4ad6463.png)
![image](https://user-images.githubusercontent.com/99383821/174219908-78cdf4a7-aa62-475d-8595-7287b157acde.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174264795-adb87951-4511-42b8-8834-aedbe11a129b.png)
就这个 ···

**Comment by imwaitingfor** [comment]
> ![image](https://user-images.githubusercontent.com/99383821/174264795-adb87951-4511-42b8-8834-aedbe11a129b.png) 就这个 ···

这个点是内置的内容，无法修改
