### ISSUE TITLE
标签相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#121]
标签内的文字偏下了
字号12px的文字行高是20px
![image](https://user-images.githubusercontent.com/92357451/173317063-ba5f4d5e-e6bc-401d-8756-e21472548dfc.png)

**Comment by fayfayfairy** [comment]
状态标签的样式与设计稿不一致
![image](https://user-images.githubusercontent.com/92357451/173326464-e941cce2-663d-4af6-a75b-281d77b4875d.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/174218579-1ffc5303-5512-4aad-92d8-14ea41be422e.png)
![image](https://user-images.githubusercontent.com/99383821/174218715-858766ed-83da-4f67-acad-f4971104bcb5.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/179466231-12db1532-bee6-4257-8852-3667d2d61170.png)
未修改

![image](https://user-images.githubusercontent.com/99383821/179467154-4fa226a2-2e2e-4a89-b391-a6d0a6030765.png)
两边边距是8px

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/179466231-12db1532-bee6-4257-8852-3667d2d61170.png)
未修改

![image](https://user-images.githubusercontent.com/99383821/179467154-4fa226a2-2e2e-4a89-b391-a6d0a6030765.png)
两边边距是8px
