### ISSUE TITLE
表格

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#132]
表格缺少可伸缩列的样式
![image](https://user-images.githubusercontent.com/99383821/175923843-8bac89a8-3e09-4375-beae-e6c89481e3cb.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/189803937-36a1cecf-6b15-4197-98d6-2a573c536179.png)
固定列

**Comment by liuxy0551** [comment]
文档已经更新

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/195490520-98b455ac-597a-459d-90b7-cec99dc341a0.png)

**Comment by liuxy0551** [comment]
done
