### ISSUE TITLE
Theme图标替换

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#142]
![image](https://user-images.githubusercontent.com/92357451/184277440-c6e43b54-74f4-4bc6-8920-51bda1675a8d.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/184277574-b307f0d3-de98-44dd-9fe7-386179e04211.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185879903-f97c3eca-1999-437d-b662-c91dbaa14638.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185881763-630a8f94-f7de-4771-b10e-c6bfb9ac35e1.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185882642-861b9572-5099-4d53-9b49-2500255cbd93.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185885332-ffeff385-ce6b-45c7-939c-368310e1f577.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185890514-e87c4ad5-fa07-4701-a686-f6a83fef6361.png)
这里hover状态的图标色号为#64698B

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185892286-e50658b4-553b-48ae-9e7e-5829909aaeaa.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185892853-816f648e-f81b-46a9-a015-04501c586afe.png)
icon的default状态填充色#B1B4C5  hover状态填充色#64698B

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185893754-69901632-9704-445b-a2a7-77005ae967e7.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185894394-d3667bbd-070e-4cc7-b96a-10249a0d3afa.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185895296-770e7920-30a1-4f0e-92d2-22e79709fc55.png)
![image](https://user-images.githubusercontent.com/92357451/185895392-d4033e6e-2ebe-40de-afe1-8391bf13d687.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185901092-d4d2e0af-342c-464e-8a1b-750c12bacf01.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185901633-cb8460a0-10cb-4bda-a9a1-ac7a81d3dfd3.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/185901955-0cbfda4b-e5f2-4b95-bb56-3f3c25cbf7ba.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/192739383-1f640686-08ab-48a6-b8a9-bf42feef9014.png)
![image](https://user-images.githubusercontent.com/99383821/192739531-8247ecfa-5f09-44ab-a014-d81e06f5c08f.png)
