### ISSUE TITLE
UI5.0 - Layout

### ISSUE THREAD

**Issue by xigua-Jn** [DTStack/ant-design-dtinsight-theme#146]
![image](https://user-images.githubusercontent.com/66997829/185135781-5525e9d6-f7a2-4817-96f5-58aac1201370.png)

header 文字颜色

**Comment by xigua-Jn** [comment]
![image](https://user-images.githubusercontent.com/66997829/185136693-b4548e8b-e378-43fc-b612-1b5a80f787f0.png)

.user-info

**Comment by kongshan-zhuyu** [comment]
已经解决#164
