### ISSUE TITLE
UI-5.0 Table

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/ant-design-dtinsight-theme#147]
表格行高度目前为44px ，无法通过设置 Table 的size属性 调节

**Comment by HaydenOrz** [comment]
表格数据为空时，empty image 过高导致出现滚动条
![image](https://user-images.githubusercontent.com/58289241/185885348-8bcb897b-e5e1-4162-9029-858f31627c43.png)

**Comment by Zaoei** [comment]
目前表格行高度是固定 44px
```
.ant-table-tbody > tr{
    height: 44px;
    box-sizing: border-box;
    line-height: 44px;
}
```

UI 5.0 表格行高可以随着内容发生改变。如：
![image](https://user-images.githubusercontent.com/46592356/189046756-f619c13e-8e92-468b-8905-d54b3bd553ca.png)

**Comment by Zaoei** [comment]
由于表格行高导致内容高度与原本存在差异。
左侧为 ui 5.0效果，右侧为原ui效果
![image](https://user-images.githubusercontent.com/46592356/191698442-d9a1ed5b-db3c-41c9-8c22-9dfe42cdced7.png)

**Comment by mortalYoung** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/18719701/192519982-1e8182f3-2568-4c71-aad3-62bedd53fc18.png">
 Table 有一个问题 当我添加  dt-table-fixed-contain-footer class 的时候，本意是为了让 Pagination 居右，但是意外地发现该 class 会给 Table 添加 border 属性，但是设计稿中不存在 border

**Comment by Zaoei** [comment]
表格的高度应为 44 px。在开启了checkout的情况下变为了 51 px。
![image](https://user-images.githubusercontent.com/46592356/192989117-db5b4939-1817-4994-a4be-e3cec9c680e1.png)

造成原因为：被 checkout 的 pedding 撑开。导致变成了 51 px。
![image](https://user-images.githubusercontent.com/46592356/192989477-5d483a0b-d157-430f-8571-b18e4fb104da.png)

**Comment by Zaoei** [comment]
表格行高度由43px的内容。1px的底边构成

**Comment by LuckyFBB** [comment]
使用嵌套表格时，发现子表格样式错位，初步排查是ant-table-cell样式造成的问题
![image](https://user-images.githubusercontent.com/38368040/194701860-1d85ea8e-2ce9-40f4-9555-87cb3df06e03.png)

期待的结果
![image](https://user-images.githubusercontent.com/38368040/194701954-f50f779e-5fa7-445f-9a37-4d8dd3a40ec2.png)

**Comment by Zaoei** [comment]
分页器在表格中没有上下居中
![image](https://user-images.githubusercontent.com/46592356/195266118-d5b820f7-ada5-4c59-b09c-d6ef5248a681.png)

**Comment by Zaoei** [comment]
th 字体颜色 #3d446e
![image](https://user-images.githubusercontent.com/46592356/195293297-9773621e-21e6-478b-8345-a82f60c48690.png)

**Comment by kongshan-zhuyu** [comment]
> dt-table-fixed-contain-footer

UI5.0仅支持default和small的大小，default下为44，small下为36

**Comment by kongshan-zhuyu** [comment]
> 表格行高度目前为44px ，无法通过设置 Table 的size属性 调节

UI5.0仅支持default和small的大小，default下为44，small下为36
