### ISSUE TITLE
UI-5.0 Tabs

### ISSUE THREAD

**Issue by HaydenOrz** [DTStack/ant-design-dtinsight-theme#148]
1. Tabs 组件 Nav和content之间的margin
![image](https://user-images.githubusercontent.com/58289241/185880196-736680fe-b014-479f-ac24-8bab646999d4.png)

2. 为不同样式的Tabs 分别提供类样式
![image](https://user-images.githubusercontent.com/58289241/185879943-e8e1dad6-c833-422e-bd26-26bda4e327c2.png)

**Comment by mortalYoung** [comment]
![image](https://user-images.githubusercontent.com/18719701/192421400-99f9dd32-8bac-4d82-8fe2-dc9c2988a8f5.png)
如图，设计稿的样式中 padding 的大小为 16px fontSize 的大小为 14px lineHeight 为 22px 底下蓝色滚动条也需要注意一哈

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/199657903-11929736-4a2f-4571-a0bf-7cf141a1bb40.png)
设计稿中新增侧边的展示，hover时跟顶部导航一样，在default的基础上加一个F5F5F8的底
![image](https://user-images.githubusercontent.com/55699373/199658137-08c7e511-09d5-4611-8ac0-9e828419d4e0.png)

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/200291852-7a26b53f-c408-4a8b-9656-ec7089eee96f.png)
颜色为EBECF0
