### ISSUE TITLE
UI5.0 - Search

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#149]
Search 组件的样式异常

![Snipaste_2022-09-01_16-25-28](https://user-images.githubusercontent.com/46592356/187868363-4fc8f49b-39bc-4dfa-895e-3697d5a12a60.png)

**Comment by Zaoei** [comment]
antd v4.22.5

**Comment by Zaoei** [comment]
未在 `/theme/dt-theme/index.less`、`/theme/dt-theme/reset.less` 中引入 `./default/input.less` 导致

**Comment by kongshan-zhuyu** [comment]
重复关闭
