### ISSUE TITLE
UI5.0 - Modal

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#153]
5.0 规范
![image](https://user-images.githubusercontent.com/46592356/188453999-414a5a60-dbaa-42d2-a4cf-075ef1c65d7c.png)

当前 theme：
![image](https://user-images.githubusercontent.com/46592356/188454076-803a73a6-748d-4158-95f4-1c755d538107.png)
![image](https://user-images.githubusercontent.com/46592356/188454149-608234d7-07c8-4a56-a74c-55065eab7641.png)

**Comment by LuckyFBB** [comment]
![image](https://user-images.githubusercontent.com/38368040/190962042-4f404734-28df-4f98-875c-f5ccd5384203.png)

删除 hover 时，背景变成白色
