### ISSUE TITLE
UI5.0 - Table.border

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#154]
表格外边框颜色应为： #EBECF0

目前为：#D8DAE2
![image](https://user-images.githubusercontent.com/46592356/188456598-8206543e-0894-4628-aca3-422dbb60f36d.png)

**Comment by LuckyFBB** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/38368040/188570364-98fc66ea-8052-4f02-97a9-5e1e3ec55312.png">
以前这个类名是不带border的，为什么这次改成了带有border的讷？

**Comment by kongshan-zhuyu** [comment]
> <img alt="图片" width="543" src="https://user-images.githubusercontent.com/38368040/188570364-98fc66ea-8052-4f02-97a9-5e1e3ec55312.png">
> 
> 以前这个类名是不带的，为什么现在改成这个？

https://github.com/DTStack/ant-design-dtinsight-theme/commit/771c14fbb02d92df302f06e40d43156882f7ce7f
