### ISSUE TITLE
UI5.0 - Table.Row.Height

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#155]
提供一个类名，用来支持表格内进行表单操作，需要行高为 64 的情况
![image](https://user-images.githubusercontent.com/46592356/188631497-2a683e5e-91b5-4db8-aba0-b7342b8b7d04.png)

**Comment by Zaoei** [comment]
https://github.com/DTStack/ant-design-dtinsight-theme/issues/147#issuecomment-1240261480

**Comment by liuxy0551** [comment]
min-height: 44px;
