### ISSUE TITLE
UI5.0 - SiderBar

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#157]
黑色改白色

**Comment by Zaoei** [comment]
sidebar 还是黑色块，需要改成白色主题
![image](https://user-images.githubusercontent.com/46592356/191696703-c4f4fd3a-47e7-4ed9-8cc3-4a8e7afa42e5.png)

**Comment by mumiao** [comment]
需要跟UI商量，侧边和导航都是白色，看下UI规范有没有

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/191749357-ec32ca1d-67f6-4004-9368-79e413296715.png)
@liuxy0551 需要common配合更改

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/191880624-1de4dcbd-9cf7-4ec8-9f8b-222f8d9c14c8.png)
@Zaoei 子产品改的时候注意下，theme的有些样式会被覆盖
