### ISSUE TITLE
UI 5.0 Input[Search]样式

### ISSUE THREAD

**Issue by imwaitingfor** [DTStack/ant-design-dtinsight-theme#161]
升级后Search的Button样式与文档显示不一致

**Comment by imwaitingfor** [comment]
![image](https://user-images.githubusercontent.com/21350892/191444762-999e2d1b-ec08-466d-80b7-6d066ff461b6.png)
![image](https://user-images.githubusercontent.com/21350892/191444835-897c971f-1a22-4cb9-b35b-e21efba5b62b.png)

**Comment by mumiao** [comment]
与 https://github.com/DTStack/ant-design-dtinsight-theme/issues/149 重复，提**issues** 和 解决 **issues**需要看下是不是有重复的， @imwaitingfor 尤其是解决的， 要去重下 @kongshan-zhuyu

**Comment by LuckyFBB** [comment]
![image](https://user-images.githubusercontent.com/38368040/191750955-ca35bc0c-657e-4a67-bfc8-87eac15f5f37.png)
高度略微不一致

![image](https://user-images.githubusercontent.com/38368040/191751070-c706d599-8d1a-42bd-bee8-27a0536ab853.png)
当我们输入输入框时，搜索框的 border 会被遮盖

**Comment by kongshan-zhuyu** [comment]
> ![image](https://user-images.githubusercontent.com/38368040/191750955-ca35bc0c-657e-4a67-bfc8-87eac15f5f37.png) 高度略微不一致
> 
> ![image](https://user-images.githubusercontent.com/38368040/191751070-c706d599-8d1a-42bd-bee8-27a0536ab853.png) 当我们输入输入框时，搜索框的 border 会被遮盖

![image](https://user-images.githubusercontent.com/55699373/191886405-e67c8352-0f9b-4243-a0d8-97a57ab235aa.png)
把这个去掉
