### ISSUE TITLE
UI 5.0 checkbox样式

### ISSUE THREAD

**Issue by imwaitingfor** [DTStack/ant-design-dtinsight-theme#165]
![image](https://user-images.githubusercontent.com/21350892/191644682-f49fcba5-8af3-4aa9-977d-dab59faeba1f.png)
![image](https://user-images.githubusercontent.com/21350892/191644764-8e4f3aa0-1e41-45c6-b5a4-08c05a511288.png)

**Comment by imwaitingfor** [comment]
Theme文档CheckBox只有横排的，没有纵排的

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/191650941-1043f6f4-0efa-4562-a4ad-3d2660be001c.png)
样式错乱是由于产品内部的样式覆盖了去掉即可
