### ISSUE TITLE
UI 5.0 Drawer 

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#169]
在资产中表现形态为

![image](https://user-images.githubusercontent.com/38368040/191713315-112c5dbb-7192-4c96-8731-e949148c205f.png)

1. header的padding-bottom为0，是 RC 的样式影响，components/dragDrawer/index.scss
 
![image](https://user-images.githubusercontent.com/38368040/191713627-433826df-13d5-441a-ba14-6836c7484764.png)

2. theme 中已经写了背景色，但是在项目中尚未生效，不确定是否theme版本不对或者是其他问题

![image](https://user-images.githubusercontent.com/38368040/191714522-abdb18a2-705f-4b58-a958-3bd071ff8a54.png)

**Comment by kongshan-zhuyu** [comment]
> 在资产中表现形态为
> 
> ![image](https://user-images.githubusercontent.com/38368040/191713315-112c5dbb-7192-4c96-8731-e949148c205f.png)
> 
> 1. header的padding-bottom为0，是 RC 的样式影响，components/dragDrawer/index.scss
> 
> ![image](https://user-images.githubusercontent.com/38368040/191713627-433826df-13d5-441a-ba14-6836c7484764.png)
> 
> 2. theme 中已经写了背景色，但是在项目中尚未生效，不确定是否theme版本不对或者是其他问题
> 
> ![image](https://user-images.githubusercontent.com/38368040/191714522-abdb18a2-705f-4b58-a958-3bd071ff8a54.png)

第二个已经修复，第一个给rc提吧
