### ISSUE TITLE
UI5.0 - Menu

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#175]
当前左间距为10像素，ui5.0 要求为8像素
![image](https://user-images.githubusercontent.com/46592356/192458752-1dc45d35-6f88-43fe-b754-4ab5cd79524f.png)

**Comment by Zaoei** [comment]
当前一级标题高度为 48px，需改为 56px
![image](https://user-images.githubusercontent.com/46592356/192459591-1c60dcc8-24d4-4a17-847e-c67dd33fbe6c.png)

**Comment by liuxy0551** [comment]
已同步到 dt-common/feat_8.x.y_UI5.0 分支
