### ISSUE TITLE
UI 5.0 - Form - Input

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#190]
在表单校验异常的场景下，再次获取表单焦点，边框为蓝色。正确为红色。
![image](https://user-images.githubusercontent.com/46592356/194740855-568e2b57-add1-4e4b-a834-a2c7b6cc9aeb.png)

造成原因为:
`input.less` 文件
```
.ant-input:focus{
    border-color: #005CE6 !important;
    box-shadow: none;
}
```

**Comment by liuxy0551** [comment]
已同步到 dt-common/feat_8.x.y_UI5.0 分支
