### ISSUE TITLE
UI 5.0 Select - multiple - height 

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#191]
左侧为 select ，mode 为 “multiple”，可以看到与右侧的 input 高度不同。
![image](https://user-images.githubusercontent.com/46592356/194742134-465ef962-8ceb-4ab8-88b4-e4e2c16401e5.png)

造成原因：
`cascader.less`设置了高度为 24px 导致。
```
.ant-select-multiple{
    .ant-select-selector{
        .ant-select-selection-item{
            background: #F9F9FA;
            height: 24px;
            line-height: 20px;
            border: 1px solid #EBECF0;
        }
    }
}
```

**Comment by liuxy0551** [comment]
已同步到 dt-common/feat_8.x.y_UI5.0 分支
