### ISSUE TITLE
UI5.0 - Table - checkbox

### ISSUE THREAD

**Issue by Smallnuo** [DTStack/ant-design-dtinsight-theme#192]
checkbox 与表格内容未对齐，初步排查是因为theme中给.ant-checkbox-wrapper 设置了 padding 导致
分支：easyIndex/feat_5.3.x_indexDefined
验证模块：运维中心 --> 数据模型 --> 数据模型详情 --> 版本变更
![image](https://user-images.githubusercontent.com/51777605/194746261-459cca48-fb57-4d20-b064-4f9702638830.png)

**Comment by liuxy0551** [comment]
验证模块：指标中心 --> 数据模型 --> 数据模型详情 --> 版本变更
