### ISSUE TITLE
通知提醒弹窗

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#201]
![image](https://user-images.githubusercontent.com/92357451/194985173-c0aa6093-742d-48d9-8b42-f3f039e2819b.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/194987920-1e9b3a6e-c191-447f-86ef-13c3aa5832c0.png)

**Comment by liuxy0551** [comment]
和 #142 相同
