### ISSUE TITLE
选择器

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#205]
![image](https://user-images.githubusercontent.com/92357451/195071779-b1fb49d5-9d74-48e4-a1d8-5330050d7b3f.png)

**Comment by liuxy0551** [comment]
@Zaoei 帮忙看下复现路径

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/197457044-e8f5fba6-875a-42fa-a80a-cba1535c13cb.png)

**Comment by liuxy0551** [comment]
@fayfayfairy 第一张截图的边框颜色已经正常
![image](https://user-images.githubusercontent.com/34759874/199147133-2976ffd6-7c34-48c1-a635-9c3284ece6e0.png)

**Comment by liuxy0551** [comment]
@Zaoei 灰灰的第二张截图请子产品自行修复。

修复建议：ellipsisText 下的 vertical-align 值去除或者为默认值 baseline 即可
![image](https://user-images.githubusercontent.com/34759874/199147283-074552b7-2671-40b3-872b-373bb248871e.png)
![image](https://user-images.githubusercontent.com/34759874/199147289-30fe69c4-6f3f-4031-960b-c64dde6ec0dd.png)
