### ISSUE TITLE
UI5.0 - Checkbox - height

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#213]
checkbox height 32px。导致无法居中
![image](https://user-images.githubusercontent.com/46592356/195295522-9b0488c4-2467-4e55-8a1f-ace4cfc0a8b1.png)

**Comment by liuxy0551** [comment]
是不是没有 merge 最新的，已经修了

https://github.com/DTStack/ant-design-dtinsight-theme/pull/209/files

**Comment by Zaoei** [comment]
重复 issuse，关闭
