### ISSUE TITLE
UI5.0 - Step

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#214]
## 在资产内展示为：
![image](https://user-images.githubusercontent.com/46592356/195301589-e062d297-9687-4558-bd54-8fa17051eb76.png)

## 应为：
![image](https://user-images.githubusercontent.com/46592356/195302203-3c2f0c38-6cbb-4500-a5b4-579bc7f5ba67.png)

背景也需要改

## 复现模块
数据资产 -> 数据质量 -> 规则配置 -> 规则集

**Comment by liuxy0551** [comment]
theme 新增 steps className: `dt-steps-header`，资产的同名了，需要删除资产中 `dt-steps-header` 的样式
![image](https://user-images.githubusercontent.com/34759874/195813150-d60b96e7-eb19-407f-8bf5-71697d73cf3b.png)
