### ISSUE TITLE
index和reset冗余是否考虑删除

### ISSUE THREAD

**Issue by kongshan-zhuyu** [DTStack/ant-design-dtinsight-theme#220]
与default文件夹中的index和reset文件相同，是否删除外部的文件
![image](https://user-images.githubusercontent.com/55699373/195805079-76952f1d-426e-4621-bc53-61623621bc40.png)
即只保留第二种方式引入
![image](https://user-images.githubusercontent.com/55699373/195805300-2c52a828-d01d-4ae8-95e0-f0411fce1d32.png)

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/200222273-443b1039-e5a3-4e6a-8161-fc0a17b38e71.png)
