### ISSUE TITLE
UI5.0 - Form - error - height

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#227]
报错信息取消高度 20 的限制，让它自适应。

![image](https://user-images.githubusercontent.com/46592356/196098909-0c14b7dd-980e-42e0-9d8a-b0c5dab96bfd.png)

资产 -> 数据地图 -> 搜索 -> 表结构

**Comment by Smallnuo** [comment]
升级后新建目录后报错时高度未撑开
![image](https://user-images.githubusercontent.com/51777605/201591707-66eadd0e-751d-42f7-897b-86e34f1950f3.png)
