### ISSUE TITLE
UI5.0 - Tag - margin

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#229]
下图中的文本后的 x 其实是 icon，不包含在文本内，但是由于没有间距进行区分，导致看起来是一体的。

![image](https://user-images.githubusercontent.com/46592356/196103894-d5e05a3f-3077-42dd-8620-6d0092cb1223.png)

在文本和 x 号之间增加 2px 的间距。

资产 - 元数据 - 数据地图 - 表结构

**Comment by liuxy0551** [comment]
done

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/196148269-de1c5da3-fdf3-4519-8653-c277b4a9e98f.png)
