### ISSUE TITLE
UI5.0 - Nav

### ISSUE THREAD

**Issue by OnlyFlyer** [DTStack/ant-design-dtinsight-theme#232]
新的 nav 导航栏色调应为浅色

![image](https://user-images.githubusercontent.com/19942622/196112195-dbfe096a-cb57-4f4e-985d-2bf4b456d831.png)

应用：dt-insight-studio
分支：batch/feat_5.2.x_UI5.0_dilu
路由：任一路由

解决方案：

![image](https://user-images.githubusercontent.com/19942622/196112626-d9fb0c1e-2be9-4839-992a-f7c519f727ce.png)

位置：dt-common/src/components/nav/style.scss

![image](https://user-images.githubusercontent.com/19942622/196113008-0e786ca3-82a7-4d8a-b17e-79ca792d4857.png)

**Comment by liuxy0551** [comment]
done

**Comment by liuxy0551** [comment]
merge dt-common/feat_9.x.y_UI5.0
