### ISSUE TITLE
pagination 分页高度不对

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#235]
![image](https://user-images.githubusercontent.com/38368040/196161010-380a9182-3acd-4e45-ac1e-437c8cb4ad13.png)

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/196167910-5414ad82-a862-45ac-8833-2a9161dce610.png)

**Comment by liuxy0551** [comment]
> ![image](https://user-images.githubusercontent.com/55699373/196167910-5414ad82-a862-45ac-8833-2a9161dce610.png)

@LuckyFBB @Zaoei 资产加一行代码即可解决：
![image](https://user-images.githubusercontent.com/34759874/196181522-c526d6bb-a206-47a4-abdc-65c897d920d1.png)
