### ISSUE TITLE
TreeSelect checkbox 尚未居中

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#248]
![image](https://user-images.githubusercontent.com/38368040/196443924-9c1fd6b5-3fc5-4d7e-aac4-d48908fb7df3.png)

**Comment by liuxy0551** [comment]
选项文字过多时不会换行
![image](https://user-images.githubusercontent.com/34759874/198996796-30c7af92-c17b-49ba-b2ce-0b5d91cca7ee.png)

**Comment by liuxy0551** [comment]
done
