### ISSUE TITLE
Table empty 居中

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#249]
![image](https://user-images.githubusercontent.com/38368040/196681196-2174738c-3392-443d-b1c2-b18bfbeae72e.png)

**Comment by liuxy0551** [comment]
1、antd 默认情况：![image](https://user-images.githubusercontent.com/34759874/198998489-0d930d01-9004-4948-a914-22df0037421d.png)

2、垂直居中：
![image](https://user-images.githubusercontent.com/34759874/199002038-49446ad8-d594-424e-90c1-e50f585c77cb.png)

**Comment by liuxy0551** [comment]
@fayfayfairy 建议保持 antd 的设计，即上下 margin 32px。 

因为在子产品很多页面表格上面还有内容，表格只展示上半部分，如果固定高度还垂直居中，第一眼会看不到缺省图，比如以下两张图的对比
![image](https://user-images.githubusercontent.com/34759874/199002660-f871bf51-889d-4eb4-a72e-2e3f6feef6ec.png)

![image](https://user-images.githubusercontent.com/34759874/199002601-835dbddb-792e-4dc2-8744-288bad99b732.png)

**Comment by liuxy0551** [comment]
@LuckyFBB 资产传入自定义缺省图时带上下 margin 即可，仿照 antd 的
![image](https://user-images.githubusercontent.com/34759874/199151584-fe929414-e385-44e4-af0b-99be98d5785c.png)

**Comment by liuxy0551** [comment]
和灰灰沟通后确认：Table 下的 Empty 添加 margin: 32px 0; 同时图片大小调整为 80px；
