### ISSUE TITLE
checkbox 样式问题

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#255]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/38368040/197678057-d384746e-6976-4754-aa48-37889e603b42.png">

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/197956493-241345a3-494f-4fce-bdd2-3a82ada9a3db.png)

**Comment by liuxy0551** [comment]
图标替换问题在 #280
