### ISSUE TITLE
Tag 5.0 UI 

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#256]
缺少禁用样式

![image](https://user-images.githubusercontent.com/99383821/197679489-99b4dc3e-3345-4a37-8b78-d48c8a1f97b3.png)

设计稿地址
https://share.lanhuapp.com/#/invite?sid=lXkOohZa
分享人: admin
蓝湖团队: 数栈UI设计规范
相关项目: UI 5.0
链接有效期: 20221025~20221108

**Comment by liuxy0551** [comment]
Tag 禁用：
![image](https://user-images.githubusercontent.com/34759874/199192839-8225c72e-b25c-47db-856f-8a33d2b37ad3.png)


多选框禁用在 Select 查看
![image](https://user-images.githubusercontent.com/34759874/199192788-9fba1c45-9f39-43c6-a0f4-f4512c68df06.png)
