### ISSUE TITLE
5.0 --表格右对齐

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#267]
theme增加表格数字右对齐

![image](https://user-images.githubusercontent.com/99383821/198993362-69c960b7-5a28-4da4-89c3-563acc0c9f6b.png)

**Comment by daxi1** [comment]
输入框不能随列宽去自适应
![image](https://user-images.githubusercontent.com/99383821/198526933-e313b2ca-156f-488b-ab1e-fbf8b5cdff5f.png)

**Comment by daxi1** [comment]
表格有滚动条占位
![image](https://user-images.githubusercontent.com/99383821/198541268-10f5a2fd-20ac-4660-83e0-b9c5ac91b6fb.png)

**Comment by imwaitingfor** [comment]
> 输入框不能随列宽去自适应 ![image](https://user-images.githubusercontent.com/99383821/198526933-e313b2ca-156f-488b-ab1e-fbf8b5cdff5f.png)

这个问题标签子产品内部已解决，在对应文档应该也是勾过了，可以去验证一下

> 输入框不能随列宽去自适应 ![image](https://user-images.githubusercontent.com/99383821/198526933-e313b2ca-156f-488b-ab1e-fbf8b5cdff5f.png)

这个问题标签子产品内部已解决，在对应文档应该也是勾过了，可以去验证一下

**Comment by imwaitingfor** [comment]
> 输入框不能随列宽去自适应 ![image](https://user-images.githubusercontent.com/99383821/198526933-e313b2ca-156f-488b-ab1e-fbf8b5cdff5f.png)

这个问题标签子产品内部已解决，在对应文档应该也是勾过了，可以去验证一下
