### ISSUE TITLE
UI5.0 Table

### ISSUE THREAD

**Issue by liuxy0551** [DTStack/ant-design-dtinsight-theme#269]
scroll 示例中 y 的值为 true  
![image](https://user-images.githubusercontent.com/34759874/198532180-9f421f04-fb96-4f59-90cc-9180d372bdbd.png)

**Comment by mumiao** [comment]
![image](https://user-images.githubusercontent.com/22880945/198543875-2b6e4e54-bfde-4c94-b9f7-4b473f72d78e.png)
**form**和**table**目前都是紧凑型，这个自定义类名可以删除了

**Comment by liuxy0551** [comment]
> scroll 示例中 y 的值为 true ![image](https://user-images.githubusercontent.com/34759874/198532180-9f421f04-fb96-4f59-90cc-9180d372bdbd.png)

scroll y 为 true 时，也能达到撑起表格高度的目的
