### ISSUE TITLE
UI5.0 Drawer 的 header

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#271]
![image](https://user-images.githubusercontent.com/38368040/198869116-828aa84f-8616-46ad-bb9a-3f71e26ec503.png)

**Comment by kongshan-zhuyu** [comment]
![image](https://user-images.githubusercontent.com/55699373/198952909-eff38542-5932-4a35-a364-dc9436a54abe.png)
我看好像是有线的，设计稿没更新吗

**Comment by kongshan-zhuyu** [comment]
已经与设计确认没有线，我这边修改下
