### ISSUE TITLE
UI5.0 - Transfer - button

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#274]
![image](https://user-images.githubusercontent.com/46592356/198942005-6a688fe6-7036-4ac9-a330-409d77a58f3b.png)

右图标看不见了。

造成原因是 theme 中 input.less 和 button.less 都对 ant-btn-icon-only 样式进行重写，其中 input 中把 background 设置为 none 。

**Comment by liuxy0551** [comment]
同 #264

**Comment by liuxy0551** [comment]
在 #220  中解决
![image](https://user-images.githubusercontent.com/34759874/200222363-73a77785-7315-4c52-9819-60aa389c4175.png)
