### ISSUE TITLE
UI5.0 图标替换

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#280]
![image](https://user-images.githubusercontent.com/92357451/199174329-cab56d00-0ce6-4d10-904c-161499ec5430.png)

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/199204815-a9cb0fb6-6add-4697-a7f4-076eb7ddb2bb.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/199426531-7adf973b-7477-4504-a906-01af22f9029b.png)
选择器的箭头和多选标签的关闭icon不对

**Comment by liuxy0551** [comment]
表格的筛选图标
![image](https://user-images.githubusercontent.com/34759874/199902835-90837abb-6147-471c-888d-be94b780847f.png)

**Comment by liuxy0551** [comment]
done
