### ISSUE TITLE
UI5.0 Table Filter和Sort 图标替换未成功

### ISSUE THREAD

**Issue by Smallnuo** [DTStack/ant-design-dtinsight-theme#285]
表格使用相同的类名dt-table-fixed-contain-footer，但发现在指标中心图标替换成功，运维中心图标替换失败
![image](https://user-images.githubusercontent.com/51777605/199421701-522231bb-428e-4627-9875-11b10ce7597e.png)
![image](https://user-images.githubusercontent.com/51777605/199421812-f6f84b9b-1527-4c27-927b-69e72ea42ebd.png)
验证分支：easyIndex/feat_5.3.x_basic
由于指标目前v51环境不在维护，可以在devops环境进行验证
地址：http://uicfront-default-521-easyindex.beta52.devops.dtstack.cn/#/login
账号：admin@dtstack.com
密码：DrpEco_2020

**Comment by liuxy0551** [comment]
theme 暂时无法替换表格的筛选图标，先保持原样
