### ISSUE TITLE
Alter & Modal 组件样式问题

### ISSUE THREAD

**Issue by Erindcl** [DTStack/ant-design-dtinsight-theme#3]
### 「Alert 警告提示」成功状态的icon颜色与颜色规范中不一致

![image](https://user-images.githubusercontent.com/26838689/106565239-768f3400-6569-11eb-8d2e-5320dfd890c1.png)

### Modal 弹窗对话框等投影与规范中不太统一（全局问题）

![image](https://user-images.githubusercontent.com/26838689/106565310-90307b80-6569-11eb-863f-89e8c49935db.png)

**Comment by ting0130** [comment]
Alert 警告提示成功提示颜色已改好，设计验收为未改之前的代码
