### ISSUE TITLE
UI5.0 Tabs 支持iconfont

### ISSUE THREAD

**Issue by Smallnuo** [DTStack/ant-design-dtinsight-theme#332]
![image](https://user-images.githubusercontent.com/51777605/200751975-c8c414bb-9f6a-4c40-a995-71a1a4d0c1fd.png)
目前只支持 Ant Design 提供的图标，使用 iconfont 上的图标会紧贴和大小不对
目前 iconfont 数栈使用方式有 font class 和 symbol 两种

**Comment by liuxy0551** [comment]
给个分支和复现场景吧， theme 里没有引入 iconfont 不好测试

**Comment by liuxy0551** [comment]
easyIndex/feat_5.3.x_uiCheck
![image](https://user-images.githubusercontent.com/34759874/201024251-c30eceda-2ee1-4ea5-966f-cd20394bcfda.png)

**Comment by liuxy0551** [comment]
建议子产品处理 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/34759874/205227593-3c32ca8d-3ab4-40ca-8e31-c5e0e65c1da6.png">
