### ISSUE TITLE
UI5.0 - form - table

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#342]
把 `table `包在 form 内，并对 `form` 的 layout 设置为 `vertical `，会导致写在`table`内的表单匹配 `.ant-form-vertical .ant-form-item-row` 样式。导致位置异常。如下
![image](https://user-images.githubusercontent.com/46592356/200799375-9f310035-f69a-4d7c-a6c6-0cddce8c58a4.png)

分支： dataApi/feat_5.3.x_UI5.0
位置： api管理 -> 注册api -> 步骤二参数配置

**Comment by liuxy0551** [comment]
commit: https://github.com/DTStack/ant-design-dtinsight-theme/commit/28e2cbbf5dd12263d6f38c9be47964958655c864
