### ISSUE TITLE
分页器右边距

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#362]
![image](https://user-images.githubusercontent.com/92357451/201275274-b1902423-fcc9-4744-a00d-5a6cb60ad0de.png)
右边距是16px

**Comment by LuckyFBB** [comment]
资产+1
![image](https://user-images.githubusercontent.com/38368040/201807856-c88a67db-80f4-44f1-8a0c-4927f4adba53.png)
