### ISSUE TITLE
Modal.confirm 样式不对

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#371]
![image](https://user-images.githubusercontent.com/38368040/201806656-936dcaf9-53af-4389-a884-e6974220e9da.png)

![image](https://user-images.githubusercontent.com/38368040/201806827-46ae61ae-f27d-46b4-bd1b-60abad6d23bc.png)

**Comment by kongshan-zhuyu** [comment]
https://github.com/DTStack/ant-design-dtinsight-theme/issues/423
