### ISSUE TITLE
切换子产品的过渡页面

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#380]
更改背景颜色以及显示样式：
![image](https://user-images.githubusercontent.com/92357451/202140964-81fbf8e2-1472-4c89-a5f6-bf42c1afd032.png)

设计稿已更新至蓝湖
https://share.lanhuapp.com/#/invite?sid=lXxRkxm7
分享人: admin
蓝湖团队: 数栈UI设计规范的团队
相关项目: UI 5.0
链接有效期: 20221116~20221130

**Comment by fayfayfairy** [comment]
在这里
![image](https://user-images.githubusercontent.com/92357451/205032535-81567729-53d9-4f20-b654-3ababfe171ed.png)

**Comment by fayfayfairy** [comment]
去掉子产品图标展示，文字加大
![image](https://user-images.githubusercontent.com/92357451/205572907-a863c2d5-163c-41b2-8b0e-a83a79d9f39e.png)

**Comment by fayfayfairy** [comment]
跟61讨论后修改距离顶部间距为30%*页面高度
![image](https://user-images.githubusercontent.com/92357451/205578098-20ebd1ef-2f4c-4118-8aa0-c3317c27bb33.png)

**Comment by liuxy0551** [comment]
done
