### ISSUE TITLE
表格顶部的线

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#385]
![image](https://user-images.githubusercontent.com/92357451/202374354-565298f6-e5e3-4695-8531-2d307fd17134.png)
线的颜色是##EBECF0

**Comment by kongshan-zhuyu** [comment]
表格顶部的线可以用`dt-table-top-border`添加，空隙问题是一个通用问题，只会在浏览器特殊的缩放比例出现，原因参考：
[Issue 1120347](https://link.segmentfault.com/?enc=yNBO7VYLBw5MKYoZvT4GJg%3D%3D.c6hN1c1qieJ38Xiqi%2F9kFZmiZEhqpfxlTt57QLHNeJ8TW9SqCBepM5XJPEegWjcd%2F4%2FjA044Z27kj8onFiTC9A%3D%3D)
[css 页面缩放边框产生空隙相关](https://link.segmentfault.com/?enc=RdOJfPPYngFoh9jW0CGLlQ%3D%3D.6uRq7Is%2BqlbawNzrx2IYfh49ukSV%2B78zknY6DdTSpDQ1dxCaXkD8F75iHH61E6gM1GrruZT3hxpJ6coH8fkQ0Q%3D%3D)
，antd也会有这个问题，目前暂无完美的解决方案outline只在chrome94以上支持，一般情况下无此问题
