### ISSUE TITLE
UI5.0 Demo 帮助文档右侧多一个分割线

### ISSUE THREAD

**Issue by Smallnuo** [DTStack/ant-design-dtinsight-theme#387]
![image](https://user-images.githubusercontent.com/51777605/202370906-657766df-e721-4c3d-b2ed-34e1e77e198d.png)
![image](https://user-images.githubusercontent.com/51777605/202371184-af3ac765-ae7a-4a87-84e2-a876070c8397.png)
模块：项目列表 --> 行业Demo 
分支：easyIndex/feat_5.3.x_basic

**Comment by kongshan-zhuyu** [comment]
已经和UI确认过去掉这个分割线，这部分我提到commom里去

**Comment by liuxy0551** [comment]
http://gitlab.prod.dtstack.cn/dt-insight-front/dt-insight-studio/merge_requests/1833
