### ISSUE TITLE
【功能】新增标准化分页器组件

### ISSUE THREAD

**Issue by ting0130** [DTStack/ant-design-dtinsight-theme#39]
- **需求来源:** 产品经理提出简化分页诉求，UI提出统一样式诉求
- **需求描述:** 新增标准化分页器组件，包含左边有无按钮、有无跳转页码四种类型，是否需要保留页数待商定
- **需求期望效果:**

![image](https://user-images.githubusercontent.com/45486725/131281550-aecffe2e-ca68-4d2e-a9ea-a1d304182bde.png)

**Comment by AndyZjy** [comment]
Improved in UI 5.0
