### ISSUE TITLE
5.0 图标子产品内部引用

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#394]
问题描述：子产品内容引用的图标是antd的，与之前在iconfront上所建的用于替换antd图标的（DT UI 5.0 - antd）不一致
![image](https://user-images.githubusercontent.com/99383821/202610813-fd0a0a5f-fb01-471b-8f8a-7511b27666aa.png)

**Comment by liuxy0551** [comment]
done
