### ISSUE TITLE
5.0 tag

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#396]
tag引用之后关闭icon颜色样式与theme不一致
![image](https://user-images.githubusercontent.com/99383821/202659654-c501aaf8-4b4d-4eee-87a0-3f8e68894bf0.png)
![image](https://user-images.githubusercontent.com/99383821/202659873-6c03ca94-5f35-4ce5-b8d6-19fbae3c2f63.png)

**Comment by liuxy0551** [comment]
done
