### ISSUE TITLE
UI5.0 - step - height

### ISSUE THREAD

**Issue by Zaoei** [DTStack/ant-design-dtinsight-theme#401]
![image](https://user-images.githubusercontent.com/46592356/203036433-3498d360-8ecc-4309-b23d-ad7b189fd81c.png)
当前 step 的高度为 60px
```
// 24 是内容高度，18 是上下边距
24px + 18px + 18px = 60px
```

规范中高度为 56.建议上下边距改为 16px
![image](https://user-images.githubusercontent.com/46592356/203036764-885324df-73ef-4bd1-a640-ec7924ef4e77.png)

**Comment by liuxy0551** [comment]
done
