### ISSUE TITLE
搜索组件

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#414]
子产品反馈问题需要theme来修改
![image](https://user-images.githubusercontent.com/99383821/203745535-393ab171-4058-4fe9-a26b-419f3ed53928.png)

**Comment by liuxy0551** [comment]
1、margin 间距的问题，子产品将截图的两个 className 的 width 均设为 38px 即可  
![image](https://user-images.githubusercontent.com/34759874/205634652-ccf0ea6f-7b7a-408e-bbbb-a51cc5e0cfcc.png)

2、已解决
