### ISSUE TITLE
Modal对话框、Popconfirm气泡确认框、Message全局提示、Alert警告提示，图标替换以及尺寸问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#417]
删除的提示是红色的X
![image](https://user-images.githubusercontent.com/99383821/203886269-cc709098-9b63-4cef-8e5c-d8398d8cd75c.png)
![image](https://user-images.githubusercontent.com/99383821/203887105-1e13dab3-3609-4daf-994a-15fc4a97a5ad.png)
![image](https://user-images.githubusercontent.com/99383821/203887198-c8e44bbf-0eab-41f2-9928-79e7af877dd7.png)
![image](https://user-images.githubusercontent.com/99383821/203887297-2b19ee31-5569-4833-b560-d8812df1b21c.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/203888225-2ec7ba70-8f65-44c0-8d61-0f5e766cef35.png)

**Comment by liuxy0551** [comment]
done
