### ISSUE TITLE
下拉框内的空状态尺寸

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#432]
![image](https://user-images.githubusercontent.com/99383821/204995274-84112ab8-6dac-4ed2-a9c6-f1856a9c71db.png)
![image](https://user-images.githubusercontent.com/99383821/204995396-6b1f549f-7646-4ef6-b577-11e2a3306b95.png)
按照比例或者给出最小适配的尺寸，看下怎么可以解决这个问题

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/205887024-fe6d6f8c-2a9d-410f-962c-2f8ed340c2f5.png)
![image](https://user-images.githubusercontent.com/34759874/205887040-1f3159a1-6669-40e5-bc7f-1df05ee416e1.png)
