### ISSUE TITLE
table侧边有白色的空隙

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#434]
也是标签的
![image](https://user-images.githubusercontent.com/99383821/204997553-1ca02113-61e3-4602-9b6a-d89578402061.png)

**Comment by liuxy0551** [comment]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/34759874/206615396-d3609de4-d45a-428c-a836-76d25927b79a.png">

**Comment by liuxy0551** [comment]
标签自定义了滚动条样式，去除即可
<img width="441" alt="image" src="https://user-images.githubusercontent.com/34759874/206675186-83feaba9-e517-430a-af5f-2ec70497201d.png">
