### ISSUE TITLE
弹窗上的关闭icon颜色由#B1B4C5变更为#8B8FA8

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#438]
![image](https://user-images.githubusercontent.com/92357451/205204341-2083a04d-5723-4aea-8583-fc11903f8441.png)

**Comment by fayfayfairy** [comment]
关闭icon的default状态颜色#8B8FA8，hover状态##64698B

**Comment by liuxy0551** [comment]
done
