### ISSUE TITLE
input缺少文本框可拖动的样式

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#439]
![image](https://user-images.githubusercontent.com/99383821/205208755-fdda48c5-ee32-44a5-a9d7-4a489875ae95.png)
![image](https://user-images.githubusercontent.com/99383821/205209028-07d0f8d3-00f3-4ae2-be85-172dc77b1e5a.png)

**Comment by liuxy0551** [comment]
done
