### ISSUE TITLE
Modal confirm 的边距问题

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#440]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/38368040/205210004-8a982055-a395-4771-8d70-becd440c9d84.png">

![image](https://user-images.githubusercontent.com/38368040/205210024-7e145ba6-fd94-4c2a-9aac-0a08cf06a822.png)

**Comment by kongshan-zhuyu** [comment]
https://github.com/DTStack/ant-design-dtinsight-theme/issues/423
