### ISSUE TITLE
图标替换颜色改变

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#441]
![image](https://user-images.githubusercontent.com/99383821/205210762-6c8d906e-9de0-4b57-b7f1-d2f29891e33f.png)

**Comment by imwaitingfor** [comment]
复现分支：tag/test_5.3.x
路由：/labelDetails ，/tagAssessment
菜单路径：1、标签中心-->标签管理里的标签配置-->选择一个标签进入详情页-->切换到标签评分tab
2、标签中心-->标签管理里的标签评估-->下面的使用度排行列表，使用度评分列

**Comment by imwaitingfor** [comment]
import { DeleteTwoTone } from '@ant-design/icons';
还有一个DeleteTwoTone组件，颜色变浅了，但标签内部已替换，暂时无法复现

**Comment by liuxy0551** [comment]
@daxi1 antd 的评分组件用的是实心的 五角星，需要新增一个实底的五角星 svg

**Comment by liuxy0551** [comment]
评分的完成了，merge dt-common/feat_10.x.y_UI5.0 即可；  
DeleteTwoTone 未复现，如果还存在，另外提一个 issue 吧
