### ISSUE TITLE
iconfont被替换

### ISSUE THREAD

**Issue by imwaitingfor** [DTStack/ant-design-dtinsight-theme#478]
![image](https://user-images.githubusercontent.com/21350892/209776966-ce6dc68c-ef2f-4f09-b12a-093ba9a3fe84.png)
![image](https://user-images.githubusercontent.com/21350892/209776872-1468911f-e4a5-48b2-9ac1-ab3b32e4b4e5.png)
复现分支：easyIndex/test_5.3.x
复现路径：指标中心下的指标定义，选择一个待发布状态的指标，点击发布，即可看到
具体路由：/easy-index/index-define

**Comment by liuxy0551** [comment]
部分实底图标得这样使用了，因为 antd 的图标实底和空心的有些 className 是一样的   
`<ExclamationCircleFilled className="dt-anticon-exclamation-circle-fill" />`
![image](https://user-images.githubusercontent.com/34759874/209778532-271d0e82-6a7e-4bff-87f3-05e033d00ac3.png)
