### ISSUE TITLE
Table---可展开表格

### ISSUE THREAD

**Issue by imwaitingfor** [DTStack/ant-design-dtinsight-theme#483]
![image](https://user-images.githubusercontent.com/21350892/210691550-190afdff-00bd-4b43-8bc3-c6e11e2ccb66.png)
可展开表格的内容超出单行时，样式错乱
复现分支：easyIndex/test_5.3.x
复现路径：运维中心-->任务管理列表
复现路由：/operation/offline-management
环境：
172.16.82.147 172-16-82-147
172.16.84.247 172-16-84-247
172.16.82.147 uic.dttestenv.cn
172.16.84.247 rdos.dtstack.dttestenv.cn
登录账号:lewei 密码:6i35JWh3 地址:http://uic.dttestenv.cn/:82/#/login
租户：DT_demo，第一个项目

**Comment by liuxy0551** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/34759874/210695460-b31577d9-ebdf-4db8-a573-60f821fb49c8.png">

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/210697405-6d223fbc-4ce4-4e16-affa-be80282458fb.png)
