### ISSUE TITLE
横向滚动的表格，空数据状态，首屏插图未居中

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#491]
如图：
![image](https://user-images.githubusercontent.com/92357451/217225257-5ae488ea-633e-44f9-9f72-40bc2ba40ea2.png)

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/231131950-f7b581c5-571a-4ed5-a065-7f59ccd095a4.png)

**Comment by liuxy0551** [comment]
done
