### ISSUE TITLE
[bug] Steps 的样式有误

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ant-design-dtinsight-theme#493]
在设置了 dt-steps-card-container 之后，footer 的背景应该是白色。

https://github.com/DTStack/ant-design-dtinsight-theme/blob/85473d6e4af0666d9276333a40a92e9ef00c6351/theme/dt-theme/default/steps.less#L84-L85

应该是这里要改成 `#fff`

**Comment by liuxy0551** [comment]
done
