### ISSUE TITLE
删除提醒浮窗的图标

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#496]
![image](https://user-images.githubusercontent.com/92357451/219568716-56d9bc98-ce7c-4ccd-9313-a00b96a6dba8.png)

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/221471044-6255b746-527d-4530-b13a-cbb3db530137.png)
![image](https://user-images.githubusercontent.com/34759874/221471068-ee164f38-509e-4db9-ac76-6986e3b5e0ef.png)
![image](https://user-images.githubusercontent.com/34759874/221471076-4daac2ee-4558-4856-9dda-8e6f8a58559b.png)

**Comment by liuxy0551** [comment]
![image](https://user-images.githubusercontent.com/34759874/221487068-47c60df7-84ae-4f13-b03d-54ec4c2f4d55.png)
