### ISSUE TITLE
表格文字内容三行的时候高度问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#499]
theme未实现3行84px的情况
![image](https://user-images.githubusercontent.com/92357451/220270510-6f4098fe-cb37-4cb9-ac7f-10fb239a64d8.png)

**Comment by kongshan-zhuyu** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/55699373/220581096-7d496f24-718e-49e3-88e1-1bfd3bbe4178.png">
已实现增加该类名即可
