### ISSUE TITLE
Step步骤条竖直方向连接线条样式不对

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#507]
![image](https://user-images.githubusercontent.com/99383821/226263811-730e46ad-8aa6-49a9-b1ae-fb8d011189ad.png)

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/bf0387ba-236b-4a2e-b545-72c6ca2c64f0)

**Comment by liuxy0551** [comment]
done
