### ISSUE TITLE
Steps 组件的 Card 用法里面的 Form 的 padding 距离不对

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ant-design-dtinsight-theme#511]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/18719701/237005419-cf65af7a-5587-4f3a-a76d-1a37241053d0.png">
这个 padding 没撑开

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/7b5c508e-315c-48d8-a67d-e8d7fcc9cdcb)

**Comment by liuxy0551** [comment]
done
