### ISSUE TITLE
表格点击展开抽屉后，表格上选中的数据的需要显示选中样式

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#522]
选中样式底色#F5F5F8，选中样式和hover样式一致
 规范已更新https://lanhuapp.com/web/#/item/project/detailDetach?pid=37eea510-6f7d-45be-a207-9d7cbdb32235&tid=777f0ffd-06ce-4c28-8563-c9dca17ee151&see=all&project_id=37eea510-6f7d-45be-a207-9d7cbdb32235&image_id=584f6bfa-b60d-4241-8c8c-0a0296c43d47&fromEditor=true&type=image
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/99383821/936caaba-bf65-4501-ab27-a4b998b80310)
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/99383821/3c4cdb76-7c61-473f-8cd0-7e28bdd78daa)

**Comment by liuxy0551** [comment]
done
