### ISSUE TITLE
Modal title 过长和 close 按钮重叠

### ISSUE THREAD

**Issue by LuckyFBB** [DTStack/ant-design-dtinsight-theme#533]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/38368040/cead79b4-4e7b-4af4-a185-9f239f713463)

**Comment by LuckyFBB** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/38368040/f53f08d6-3a41-4e11-b3c0-2d1c5a3f9712)

**Comment by liuxy0551** [comment]
done

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/7254acb7-eb7b-455d-a34d-35f6ecbf15e8)
名称和 x 图标高度没对齐

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/93a9aacd-82ed-48fe-8c6b-41463b25039e)
已修复
