### ISSUE TITLE
Table 列点击排序后，该列背景会变透明

### ISSUE THREAD

**Issue by kiwiwong** [DTStack/ant-design-dtinsight-theme#539]
复现：
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/26963012/c00b2aa8-e62a-4d58-a0b3-e8b5d56d8982)

样式：
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/26963012/9c36dfab-938a-4a60-b088-7aa09f360f77)
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/26963012/4fe05621-3e72-4e2e-9cba-bf31dc468046)

**Comment by liuxy0551** [comment]
在 https://dtstack.github.io/ant-design-dtinsight-theme/components/table-cn/#components-table-demo-scroll 检查
