### ISSUE TITLE
部分图标大小不统一

### ISSUE THREAD

**Issue by kiwiwong** [DTStack/ant-design-dtinsight-theme#540]
禅道UI check bug-96450
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/26963012/301f336b-da3c-4471-932b-871d440933f5)

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/2297d959-fba7-426a-a43e-bf9fc2493d17)

**Comment by liuxy0551** [comment]
在 https://dtstack.github.io/ant-design-dtinsight-theme/components/icon-cn/ 检查
