### ISSUE TITLE
input 输入框在选择历史填写过的内容填入后，框会变成蓝色

### ISSUE THREAD

**Issue by KinyooZ** [DTStack/ant-design-dtinsight-theme#543]
![Screenshot 2024-01-08 at 15 44 52](https://github.com/DTStack/ant-design-dtinsight-theme/assets/104127633/e54ffe60-d3ff-47a2-935f-096b5e4373bb)
可复现：指标中心-统计周期-新增统计周期-开始/结束时间
选择历史填写过的内容再次填入时，整个输入框都会变成蓝色，应该在鼠标点击其他区域时，输入框变成默认状态，不需要一直保持蓝色

![Screenshot 2024-01-08 at 15 47 55](https://github.com/DTStack/ant-design-dtinsight-theme/assets/104127633/e62f04d0-e239-46a6-a35a-8f0572992b6d)
可复现：指标中心-指标定义-新增自定义指标-设置调度信息-指标表名称
选择历史填写过的内容再次填入时，文字内容区域会变成蓝色，应该在鼠标点击其他区域时，整个输入框变成默认状态，不需要一直保持蓝色

**Comment by liuxy0551** [comment]
Chrome 浏览器会给自动填充的输入框加上 `internal-autofill-selected` 的 className，导致背景色显示蓝色。

可以通过设置 input 的 `autoComplete="off"` 来关闭表单项填充提示；网上还有如下修改，测试后无效果，UIC 的用户名密码输入框进行了以下设置，theme 不方便统一处理，建议子产品可以自行尝试下。

``` css
input:-webkit-autofill {
    box-shadow: 0 0 0 1000px #FFF inset;
}
```
