### ISSUE TITLE
button 危险按钮的 hover/active 样式不对

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ant-design-dtinsight-theme#547]
<img width="497" alt="图片" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/18719701/bd4b9caf-7137-4dd1-a6a2-4d91a2bebf61">

![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/22f438c3-8c1d-4a2f-9261-77436fc80f6a)

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/fba4c191-19da-4a6f-a2c3-0d0bf4b428d2)


![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/92e7d06c-5455-4c17-b95c-5d8730c75076)
