### ISSUE TITLE
移除两个字之间的空格

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ant-design-dtinsight-theme#548]
<img width="596" alt="image" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/18719701/33c4cf6c-3871-4f57-96a0-01233a7c600b">

---

<img width="177" alt="image" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/18719701/01823518-f8df-40d6-9632-76b10b2de072">

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/d3bb7140-27cd-4101-9b26-69693ac3437d)

**Comment by liuxy0551** [comment]
子产品自行设置吧，不过最好大家统一动作
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/12ef2263-d2a8-4e16-9b99-8b30fba59942)
