### ISSUE TITLE
表单必填项标识没有和文字对齐

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/ant-design-dtinsight-theme#549]
<img width="99" alt="image" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/18719701/0479e8ea-c14b-4764-8e7b-c70e6e1bf9d2">

**Comment by liuxy0551** [comment]
![image](https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/8c1a98ea-19ee-44a2-ad19-5cb17ab761e2)
