### ISSUE TITLE
tree 的 checkbox 样式圆角不对

### ISSUE THREAD

**Issue by KinyooZ** [DTStack/ant-design-dtinsight-theme#561]
<img width="292" alt="截屏2024-04-29 14 54 11" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/104127633/e9ddfb64-4c7e-416a-8777-6c3225545dba">
tree 的 checkbox 样式圆角不对
应为
<img width="471" alt="截屏2024-04-29 15 12 06" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/104127633/8442f24e-f388-4926-9e48-b7bd9f8d3f19">

**Comment by liuxy0551** [comment]
<img width="1486" alt="image" src="https://github.com/DTStack/ant-design-dtinsight-theme/assets/34759874/8da3ae04-c493-4f99-b3e2-f3893b496b8c">
TreeSelect 的 Checkbox 圆角目前也是 4px，应该统一改为 2px
