### ISSUE TITLE
Tabs标签页相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#58]
![image](https://user-images.githubusercontent.com/99383821/169938903-bd5fadb1-66d8-4b0b-926d-60189e1785e0.png)
![image](https://user-images.githubusercontent.com/99383821/169939456-4dc9ef39-57fc-4313-8d39-ce42d4a51036.png)
![image](https://user-images.githubusercontent.com/99383821/169939598-71d5fa81-fcd3-4bdb-b5a0-5e09419b413d.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/169940211-fac6841b-9979-4c3e-b635-689a97bf3a8d.png)
hover状态需要加一下

**Comment by AndyZjy** [comment]
done
