### ISSUE TITLE
Notification通知提醒框相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#62]
![image](https://user-images.githubusercontent.com/99383821/170429502-2fc04377-2958-4b63-a4a7-1bf024f97a7e.png)
![image](https://user-images.githubusercontent.com/99383821/170430000-008684c9-e4d8-4aae-a25e-d6517f7829e8.png)
![image](https://user-images.githubusercontent.com/99383821/170430260-5cdbb829-2e64-45d7-8591-cb1cee21db69.png)
![image](https://user-images.githubusercontent.com/99383821/170432221-4cbf2538-03e1-47c2-852c-e9d119e12120.png)

**Comment by daxi1** [comment]
![image](https://user-images.githubusercontent.com/99383821/170432754-f5c452c1-df46-497d-926e-74a223e598a3.png)
带操作按钮的样式没有，需要补充一下；

弹窗需要默认4.5 秒后自动关闭；

**Comment by AndyZjy** [comment]
done
