### ISSUE TITLE
Modal对话框相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#63]
![image](https://user-images.githubusercontent.com/99383821/170437587-afa5d0bf-e6a1-4100-98f4-24d60760a9e0.png)
![image](https://user-images.githubusercontent.com/99383821/170437769-ecbaee29-851a-438f-9119-7f7631e58d52.png)
![image](https://user-images.githubusercontent.com/99383821/170437831-50713622-1425-4fd2-9a4e-59f3fb35dfd1.png)
![image](https://user-images.githubusercontent.com/99383821/170437936-fcd6450b-bc32-4c96-89e3-9c8c197dda0d.png)
![image](https://user-images.githubusercontent.com/99383821/170439085-28c5a195-b825-48c3-96a8-f8d1e2040784.png)
![image](https://user-images.githubusercontent.com/99383821/170439528-cbacd057-0431-4889-aa93-1366fd482c5a.png)

**Comment by shiqiWang0** [comment]
ok
