### ISSUE TITLE
Radio单选框相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#66]
![image](https://user-images.githubusercontent.com/99383821/170455101-8beddd8b-efe8-4c1b-9f02-64c9669d3704.png)

**Comment by fayfayfairy** [comment]
![image](https://user-images.githubusercontent.com/92357451/170643265-b5db19ad-ed84-4b30-b130-25b624d19867.png)
1. tab样式的的单选我们这里用不到
2. 单选文字和图标未上下居中对齐
