### ISSUE TITLE
级联选择相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#69]
![image](https://user-images.githubusercontent.com/99383821/170615989-e9c53971-346e-4bab-bc36-f02c7e58875f.png)
看下多选样式是不是需要补充
![image](https://user-images.githubusercontent.com/99383821/170616990-c50b61ac-ab8c-43d7-a598-ea4eaf0a37c7.png)
![image](https://user-images.githubusercontent.com/99383821/170617247-8d1e591a-b03a-4b97-a3b5-449249c864e5.png)

**Comment by AndyZjy** [comment]
done
