### ISSUE TITLE
选择器相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#70]
![image](https://user-images.githubusercontent.com/99383821/170618580-7fb9be0c-4dcc-4341-b98c-01c45083845d.png)
![image](https://user-images.githubusercontent.com/99383821/170618845-74963d25-d78f-4b7a-b2f5-389751be96e6.png)
![image](https://user-images.githubusercontent.com/99383821/170618843-baa47521-6835-46eb-8b48-8138b116cff8.png)
小尺寸是24px

**Comment by AndyZjy** [comment]
done
