### ISSUE TITLE
Tag标签相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#73]
![image](https://user-images.githubusercontent.com/99383821/170904711-9c378de1-e4d7-4a49-b00c-f78270ea7ce9.png)
![image](https://user-images.githubusercontent.com/99383821/170904804-a99454e0-b5fc-4cf3-a927-e7f8aa1ff1df.png)

**Comment by AndyZjy** [comment]
done
