### ISSUE TITLE
Table表格相关问题

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#74]
![image](https://user-images.githubusercontent.com/99383821/170905217-94550c5e-495c-4890-883b-30d42c3accf5.png)
![image](https://user-images.githubusercontent.com/99383821/170905729-be9f9d7c-7e78-4d6f-8bed-045267458fdf.png)
![image](https://user-images.githubusercontent.com/99383821/170905984-13756022-aae0-4371-945a-17e019260e5b.png)
![image](https://user-images.githubusercontent.com/99383821/170906384-d5d7cfed-bbe9-4b9b-8139-b7fc8a7cef65.png)
![image](https://user-images.githubusercontent.com/99383821/170906916-a2ca33f4-c89a-43dd-863d-e2d1dda7cd95.png)
表格缺少可拖拽样式和可编辑样式

**Comment by AndyZjy** [comment]
done
