### ISSUE TITLE
Collapse 折叠面板

### ISSUE THREAD

**Issue by daxi1** [DTStack/ant-design-dtinsight-theme#79]
![image](https://user-images.githubusercontent.com/99383821/170913763-88e5a73f-a12d-43d5-9681-974c6f5385fc.png)
![image](https://user-images.githubusercontent.com/99383821/170914230-0bb8b72f-0e94-4a1b-94a5-c35656e1af71.png)
![image](https://user-images.githubusercontent.com/99383821/170914391-531c7389-25e8-497d-84dc-34eddb1dad96.png)
![image](https://user-images.githubusercontent.com/99383821/170914704-f0a1689b-49de-4e22-8245-5aa82de0fba4.png)

**Comment by shiqiWang0** [comment]
字体颜色 是UI设计要求的色值，需要在确定一下

**Comment by daxi1** [comment]
颜色按照设计稿
