### ISSUE TITLE
Tag标签相关问题

### ISSUE THREAD

**Issue by fayfayfairy** [DTStack/ant-design-dtinsight-theme#81]
![image](https://user-images.githubusercontent.com/92357451/171106130-f491c9a4-1ccc-48ae-8a85-b6b1c3ed06b7.png)
圆点与文字未上下居中对齐
圆点和文字上下居中对齐 然后作为整体上下居中对齐于外边框，如设计图：
![image](https://user-images.githubusercontent.com/92357451/171106187-3f5f8935-1d55-4910-aef6-2afe0be670cd.png)

**Comment by AndyZjy** [comment]
done
